apiVersion: v1
kind: Service
metadata:
  labels:
    app: goapi
  name: goapi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: api-port
  selector:
    app: goapi 
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi-deployment
spec:
  selector:
    matchLabels:
      app: goapi 
  replicas: 2
  template:
    metadata:
      labels:
        app: goapi 
    spec:
      containers:
      - name: test-go-api
        image: localhost:5000/kasuboski/test-go-api:0ef880b4c35de0e0d6bc7c86a4218d0afe6e53a6 
        ports:
        - name: api-port
          containerPort: 8080
