resources:
- name: git-resource
  type: git
  source: 
    uri: https://github.com/kasuboski/test-go-api.git
    branch: master

- name: git-resource-image
  type: docker-image
  source:
    repository: 192.168.99.100:31892/kasuboski/test-go-api 
    insecure_registries: 
    - 192.168.99.100:31892 

jobs:
- name: build-image
  plan:
  - get: git-resource
    trigger: true
  - put: git-resource-image
    params: {build: git-resource}
